ghc-options:
  '*': -rtsopts
  geometric-algebra: -rtsopts -auto-all -O2

packages:
- '.'
- '../FRPNow'
- '../FRPNow/FRPNow-GLFW'

extra-deps:
- GLFW-b-1.4.7.3
- OpenGL-2.13.0.0
- GLURaw-1.5.0.1
- ObjectName-1.1.0.0
- OpenGLRaw-2.5.2.1
- bindings-GLFW-3.1.1.4

resolver: lts-4.2
